on: { pull_request: }
name: Build & Tests

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    name: 'Building and test for target ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
        name: 'Make ./gradlew executable'
      - run: ./gradlew --no-daemon publishToMavenLocal -D"maven.user=${{ secrets.MAVEN_USER }}" -D"maven.password=${{ secrets.MAVEN_PASSWORD }}"
        name: Build libraries
      - run: ./gradlew --no-daemon test
        name: Run tests