on: { pull_request: }

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    name: 'Building for target ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
        name: 'Make ./gradlew executable'
      - run: ./gradlew --no-daemon publishToMavenLocal -Dmaven.user=${{ secrets.MAVEN_USER }} -Dmaven.password=${{ secrets.MAVEN_PASSWORD }}
        name: Build libraries