on:
  push:
    branches:
      - main

jobs:
  build:
    uses: xolider/Kteepass/.github/workflows/build-test.yml
  deploy:
    runs-on: 'ubuntu-latest'
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          version: '21'
      - run: chmod +x ./gradlew
        name: 'Make ./gradlew executable'
      - run: ./gradlew --no-daemon -D"maven.user=${{ secrets.MAVEN_USER }}" -D"maven.password=${{ secrets.MAVEN_PASSWORD }}" publish